In [1]:
import pandas as pd

In [2]:
#loading the dataset
df = pd.read_csv('customer_shopping_behavior.csv')

In [9]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [11]:
df.columns = df.columns.str.lower()

In [14]:
df.columns = df.columns.str.replace(' ', '_')

In [45]:
df = df.rename(columns={"frequency_of_purchases_days":"purchase_interval_days"})

In [ ]:
df.isnull().sum()
df['review_rating'] = df.groupby('category')['review_rating'].transform(lambda x:x.fillna(x.median))

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [28]:
(df['promo_code_used'] == df['discount_applied']).all()

np.True_

In [32]:
df.drop(columns='promo_code_used')

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle aged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,adult
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,middle aged
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,middle aged
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,adult
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,middle aged

In [ ]:
labels = ['young adult','adult','middle aged','senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels=labels)

In [36]:
df[['age','age_group']].head()

   age    age_group
0   55  middle aged
1   19  young adult
2   50  middle aged
3   21  young adult
4   45  middle aged

In [40]:



freq_map = {
    "Fortnightly" : 14,
    "Weekly" : 7,
    "Monthly":30,
    "Quarterly":90,
    "Bi-Weekly":14,
    "Annually":365,
    "every 3 months":90
}

df['frequency_of_purchases_days'] = df['frequency_of_purchases'].map(freq_map)


df['frequency_of_purchases_days'].head(10)

0     14.0
1     14.0
2      7.0
3      7.0
4    365.0
5      7.0
6     90.0
7      7.0
8    365.0
9     90.0
Name: frequency_of_purchases_days, dtype: float64

In [41]:
df[['frequency_of_purchases_days','frequency_of_purchases']].head(10)

   frequency_of_purchases_days frequency_of_purchases
0                         14.0            Fortnightly
1                         14.0            Fortnightly
2                          7.0                 Weekly
3                          7.0                 Weekly
4                        365.0               Annually
5                          7.0                 Weekly
6                         90.0              Quarterly
7                          7.0                 Weekly
8                        365.0               Annually
9                         90.0              Quarterly

In [46]:
df

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_interval_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle aged,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,adult,7.0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,middle aged,14.0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,middle aged,90.0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,adult,7.0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,middle aged,90.0

In [48]:
%pip install  sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\tv464\appdata\local\programs\python\python312\lib\site-packages (2.1.4)
Collecting pymysql
  Using cached pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\tv464\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Using cached pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [50]:
from sqlalchemy import create_engine

# Connect to MySQL
engine = create_engine(
    "mysql+pymysql://root:tushardata@localhost:3366/project"
)

# Create table and insert DataFrame data
df.to_sql(
    name="customers",
    con=engine,
    if_exists="replace",
    index=False
)

print("Table created successfully!")

Table created successfully!